name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/continuous-deployment.yml'
      - 'scripts/sitemapGenerator.mjs'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Run ESLint
        run: yarn lint --fix=false

  Building:
    name: Compiling TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore NodeJS Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
      - name: Restore NextJS Cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ github.workspace }}/src/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Run NextJS Build
        run: yarn build
      - name: Store .next folder
        uses: actions/upload-artifact@v2
        with:
          name: nextfolder
          path: src/.next/
          if-no-files-found: error
      - name: Store public folder
        uses: actions/upload-artifact@v2
        with:
          name: publicfolder
          path: src/public/
          if-no-files-found: error

  Publish:
    name: Publish image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip docker]')"
    needs: [Linting, Building]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Download .next folder
        uses: actions/download-artifact@v2
        with:
          name: nextfolder
          path: src/.next/
      - name: Download public folder
        uses: actions/download-artifact@v2
        with:
          name: publicfolder
          path: src/public/
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: .
          tags: |
            skyrabot/skyra.pw:latest
            ghcr.io/skyra-project/skyra.pw:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: skyrabot/skyra.pw
          short-description: Website for Skyra Discord bot
